### ISSUE TITLE
special handling of #input == 1

### ISSUE THREAD

**Issue by andresy** [torch/nngraph#46]
hey,

i am curious to know why the case of #input == 1 is handled separately
e.g.
https://github.com/torch/nngraph/blob/master/gmodule.lua#L195
and for the backward:
https://github.com/torch/nngraph/blob/master/gmodule.lua#L266
https://github.com/torch/nngraph/blob/master/gmodule.lua#L277

if i understand correctly, this also impacts the split, which cannot be done on tables of size 1:
https://github.com/torch/nngraph/blob/master/node.lua#L50

could you give me an idea why you made this choice?

thanks!

ronan

**Comment by koraykv** [comment]
Because there are many nn modules that just expect a tensor. The default behaviour in nngraph is everything is a table of something. You can see here (https://github.com/torch/nngraph/blob/master/gmodule.lua#L171) that non-table inputs are put into a table. It made the logic in the in the rest of the system consistent to assume that every input is a table.

**Comment by fidlej** [comment]
An alternative consistent implementation could see everything as a nested table.
I.e., the input can be a tensor or a table with other tables or tensors.

**Comment by hughperkins** [comment]
The inconsistency does make trying to understand gmodule.lua quite a lot more complicated than it might otherwise be.  Lots of edge-cases and stuff.  Would making the nn modules document what they expect as input help?  Like:
```
function Linear:expectsTensor()
  return true
end
```

**Comment by koraykv** [comment]
I think we have resolved this offline already/
