### ISSUE TITLE
CAddTable and nngraph inconsistency: bad argument #1 to 'resizeAs'

### ISSUE THREAD

**Issue by ivendrov** [torch/nngraph#70]
[nn.CAddTable](https://github.com/torch/nn/blob/master/CAddTable.lua), when used with `nngraph`, throws a strange error when given a table of size 1. 

Here's a minimal test case: 

```lua
require 'nn'
require 'nngraph'

N = 1
input = nn.Identity()()

hiddens = {}
for i = 1, N do
    table.insert(hiddens, nn.Identity()(input))
end
output = nn.CAddTable()(hiddens)
net = nn.gModule({input}, {output})
net:forward(torch.Tensor(1))
```

If you change `N` to be greater than 1, this works fine. For `N` = 1, it throws the error
```
...lua/5.1/nn/CAddTable.lua:10: bad argument #1 to 'resizeAs' (torch.DoubleTensor expected, got userdata)
stack traceback:
        [C]: in function 'resizeAs'
        ...lua/5.1/nn/CAddTable.lua:10: in function 'func'
        ...lua/5.1/nngraph/gmodule.lua:253: in function 'neteval'
        ...lua/5.1/nngraph/gmodule.lua:288: in function 'forward'
```

This *seems* like undesirable / unexpected behaviour so I thought I'd bring it up, though maybe it is an intentional consequence of https://github.com/torch/nngraph/issues/46.

**Comment by hughperkins** [comment]
Question, lazy me, what happens if you pass in a single tensor?  I think ideally it would be good if it at last worked for a single tensor, which is kind of the standard way of passing a single tensor into a module, as far as I can tell.  A table with one tensor in is arguably a non-standard edge-case, eg see this assert in `node.split`, https://github.com/torch/nngraph/blob/master/node.lua#L50 .

**Comment by ivendrov** [comment]
> what happens if you pass in a single tensor?

Running `nn.CAddTable():forward(torch.Tensor(1))` gives the same error. Interesting. 

> A table with one tensor in is arguably a non-standard edge-case

Let me argue the opposite: For modules which are explicitly designed to take in a table, a table with one tensor seems a more natural edge case than just a single tensor.

**Comment by koraykv** [comment]
CAddTable is expecting a table of tensors as the name suggests, so I think the error is proper in the first case.

In the second case, nngraph actually does not have many edge cases that it checks and such, but it supports a much more flexible structure. In order to be able to do that, this was one of the design decisions that we did. By default an input is a table of something (tensor, table of tensor, table of table of , ...). This way, we settled on the current setup where if there is an input which has only one component, then that component is passed to the module. Otherwise how can we know to pass the single tensor into a say linear layer? this avoids writing code specific to different types of modules.

If a layer expects a table of some objects in the input, then it means it expects to operate several of those and having a table with one element is an edge case.
